on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: IAM Token
        id: get-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          IMAGE_NAME: ${{ github.sha }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
            --build-arg VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
            -t $IMAGE_NAME .
      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Tag and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpe0314hhhmd573u07l
          CR_REPOSITORY: supabase-chat-front
          HASH_IMAGE_NAME: ${{ github.sha }}
          VERSSION: ${{ steps.semantic-release.outputs.new_release_version }}
        run: |
          docker image tag $HASH_IMAGE_NAME cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$VERSSION
          docker image tag $HASH_IMAGE_NAME cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$VERSSION
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
