on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{hashFiles('yarn.lock')}}
          restore-keys: node_modules-

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint:ci
